site_name: QuestionPy
site_url: https://example.com
repo_url: https://github.com/questionpy-org/
repo_name: questionpy-org


plugins:
  - awesome-pages # Navigation Customization
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            [questionpy-server, questionpy-sdk, questionpy-common]
          options:
            show_root_heading: true
            docstring_style: google

theme:
#  name: readthedocs
  name: material # material specific settings
  features:
    - navigation.indexes
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  favicon: img/favicon.ico

nav:
  - Home: index.md
  - Getting Started:
      - getting_started/index.md
      - getting_started/installation.md
      - getting_started/create_qtype.md
      - getting_started/faq.md
  - ...
  - About:
      - about/index.md
      - about/license.md
      - about/roadmap.md

# TODO: In the future Versioning could become relevant (see https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/)
